### ISSUE TITLE
An user with PUID 1001 does not exist, adding an user called 'qbittorrent user' with PUID 1001

### ISSUE THREAD

**Issue by rodrigodk12** [DyonR/docker-qbittorrentvpn#108]
2022-08-01 08:25:58.124143 [INFO] A group with PGID 100 already exists in /etc/group, nothing to do.
2022-08-01 08:25:58.167758 [INFO] An user with PUID 1001 does not exist, adding an user called 'qbittorrent user' with PUID 1001
2022-08-01 08:25:58.876317 [INFO] UMASK defined as '0022'
2022-08-01 08:25:58.921622 [INFO] Starting qBittorrent daemon...
Logging to /config/qBittorrent/data/logs/qbittorrent.log.
2022-08-01 08:25:59.971709 [INFO] qBittorrent PID: 759
2022-08-01 08:25:59.979191 [INFO] Started qBittorrent daemon successfully...
2022-08-01 08:26:05.045373 [INFO] Network is up

My username :
uid=1001(rodrigo) gid=100(users) groups=100(users),27(sudo),113(ssh),992(docker)
 Why container creates a user "qbittorrent user" ?

**Comment by DeftlyMoving** [comment]
I am receiving the same issue, the PUID and PGID I use for my other containers is not recognized by qbittorrentvpn and I receive the error message.

2022-09-07 14:46:13.499332 [INFO] A group with PGID 65537 does not exist, adding a group called 'qbittorrent' with PGID 65537
2022-09-07 14:46:13.638735 [INFO] An user with PUID 1041 does not exist, adding an user called 'qbittorrent user' with PUID 1041

**Comment by DyonR** [comment]
Do you receive this error every time you start the container, or only when starting it for the first time?

**Comment by DeftlyMoving** [comment]
I receive it on each startup. My setup is running on a Synology machine, so it's possibly related to that. 

For the purposes of the application there is no functionality failing, as files are downloaded using the correct user and group (1041 and 65537) on the machine.

At least for my specific circumstances it could possibly just be a false positive message being returned?

**Comment by DyonR** [comment]
Normally it only runs on the first time, and after each update. It just checks if the user/group exist so qbittorrent runs with those user/group permissions. It also makes sure the downloaded files are the correct user/group.  
  
What it does it, it runs `grep $"${PGID}:" /etc/group`, to see if the group exists within the container, and it runs `id ${PUID}` to see if the user ID exists within the container.  
I don't see why running these commands would fail on a different system, since it is all within the container.  
  
You can maybe run `grep $"${PGID}:" /etc/group` and `id ${PUID}` from the console and see what it returns.  
Since I have no other systems to troubleshoot this on, it's hard for me to diagnose.

**Comment by DeftlyMoving** [comment]
I did run both commands, and it finds the group and user id successfully, after the initial creation of the group and user id in the container. 

I believe I have misunderstood the error message as an indication that it was not finding the group/user id on my own machine. In retrospect it makes much more sense that the message is indicating that the user/group did not yet exist in the container.

In addition, I am receiving the error message on startup because I have been updating the configuration on each restart.

Thanks for the clarification!

**Comment by DyonR** [comment]
Ah yeah, if you update the container on each restart it makes sense!  
I will adjust the error message to be more specific about that the user is not found in the container.
