### ISSUE TITLE
Is it necessary or safe to enable Anonymous Mode in BitTorrent settings menu?

### ISSUE THREAD

**Issue by thesomeotherguy** [DyonR/docker-qbittorrentvpn#117]
In BitTorrent settings menu: Tools > Options > BitTorrent > Enable anonymous mode

Since this docker container using VPN service on the inside, with those special kill-switch mechanism,

and this article says that if we are using VPN it's **_recommended_** to enable it:
https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode

> If you're using VPN, proxy or I2P, you probably want to enable **_Anonymous Mode_**

> Anonymous mode is only meant to further prevent your BitTorrent traffic from being associated to you, even when using other privacy enhancing mechanisms (such as a VPN service), by limiting the scope of the information broadcasted by the client (such as the fingerprint in the user-agent)

or just leave it to default settings?

I'm afraid that settings will override / conflicting with this container configuration inside.

**Comment by DyonR** [comment]
Personally, I do not believe anonymous mode is necessary, I never use it. It's a personal preference.  
It does **NOT conflict** with anything within the container. This container only makes it so that your connections goes through your VPN. Whatever qBittorrent settings you prefer, have no impact. Theoretically speaking, you could even use a proxy within the container.  
Anonymous mode is just an extra layer of anonymity provided by qBittorrent.  
You could do some research yourself to see what it does and if you think you would require it. You can keep it either on or off.
