### ISSUE TITLE
RESTART_CONTAINER too sensitive + container restarts result in active torrents erroring with `error: End of file`

### ISSUE THREAD

**Issue by malventano** [DyonR/docker-qbittorrentvpn#118]
In troubleshooting the occurrence of batches of active torrents erroring with `error: End of file`, I discovered that these errors popped up in conjunction with the container restarting. Tracing back the issue, it appeared that when under heavier network loads, the container was occasionally auto-restarting (`network appears offline, restarting` in the container log). Watching the activity, I noted that bandwidth was fine right up until the moment the container restarted (so the connection was actually fine). Setting `RESTART_CONTAINER = no` resolved the issue, but this workaround gives up the ability to restart the container for those cases where the VPN link does actually go down, defeating the purpose of that feature.
I see two issues compounding here (both related to heavy load / more frequent file writing):
- The `HEALTH_CHECK` / `RESTART_CONTAINER` function appears too sensitive to timeouts under heavier network loading.
- The `RESTART_CONTAINER` process does not appear to be gracefully shutting down the qBittorrent client prior to restarting the container, resulting in `error: End of file` when qBittorrent attempts to write to those same files after the restart. The chances of this are greater during heavier loads since there's a greater chance that files will be open for writes during the restart.

- *edit* this may be related to #90

**Comment by DyonR** [comment]
I do understand the concern regarding the `RESTART_CONTAINER` being too 'sensitive' regarding timeouts. It does indeed directly shutdown when 1 `ping` fails, which could be a false-positive.  
Because it currently fails when 1 `ping` fails, I will add an environment variable that allows users to customize the amount of `ping`s that `ping` will send.  
The new environment variable would be called something like `HEALTH_CHECK_AMOUNT` or `HEALTH_CHECK_PINGS`, something like that. This will allow you to set it like `10` for example, so if 10/10 `ping`s fail, it will forcefully shutdown.  
If >1/10 `ping`s succeed, the container will keep on living. I believe this would be a decent workaround.  
As far as I know, there is no direct way with OpenVPN or WireGuard to see if the connection is up/down.

**Comment by malventano** [comment]
That addresses the sensitivity, but is there any way to make the 'forcable shutdown' a bit more graceful, so that qBittorrent isn't killed while actively writing to files? Perhaps send a `kill -2` or the like to its process and wait another few seconds before restarting the container? Making the restarts less likely to trigger errors will help with the fallout caused by false positives from the pings.

**Comment by DyonR** [comment]
I will look into sending a different kill signal for the container.  
Thanks for the heads up about the README, fixed
