### ISSUE TITLE
Privoxy?

### ISSUE THREAD

**Issue by Kopernikus1979** [DyonR/docker-qbittorrentvpn#15]
Hi, privously I was using the QbittorentOpenVPN docker from Binhex but since this one has Wireguard I tried it ans seems to be working good, only thing missing is Privoxy, would it be possible to integrate this? Thx!

**Comment by DyonR** [comment]
I assume you want to have Privoxy with this container to be able to route the traffic of other containers through it. This is an obsolete method since it is now possible to route traffic directly through another Docker. SpaceInvaderOne made an excellent tutorial about this: https://www.youtube.com/watch?v=znSu_FuKFW0

If not, what would you use Privoxy for?

**Comment by Kopernikus1979** [comment]
Hi,

No, I use privoxy as proxy on my pc's to browse to torrent sites since it then uses the VPN of the container instead of having to conenct my pc to the VPN, now I use an easy on/off proxy switch in my browser whenever I want to use the VPN for my browers.

Thx

**Comment by Kopernikus1979** [comment]
Plz :-)

**Comment by DyonR** [comment]
I have decided not to add Privoxy to this container since this means more maintenance. Sorry.
