### ISSUE TITLE
Exporting torrents limited to only ten.

### ISSUE THREAD

**Issue by gderf** [DyonR/docker-qbittorrentvpn#160]
Version: qBittorrent v4.5.1
Docker image: latest, digest af2c75450243

When selecting many torrents and then right clicking, Export .torrent, only a maximum of ten torrents are placed into the download directory.

**Comment by DyonR** [comment]
Confirmed, but not an issue caused by this Docker container.  
Using a local Windows installation of qBittorrent 4.5.2 with WebUI enabled, exports only 8-10 also.  
Same with the WebUI of this Docker container.  
Not something I could fix. Best thing you could is reporting it to https://github.com/qbittorrent/qBittorrent/issues

**Comment by gderf** [comment]
A PR was generated for this problem and it looks like it might make it into 4.5.3

https://github.com/qbittorrent/qBittorrent/pull/18853

**Comment by DyonR** [comment]
Reopened because of that

**Comment by gderf** [comment]
I believe the fix for this was backported into QBT 4.5.2 about a week ago. Would it be possible to push a new image out? Thanks.

**Comment by gderf** [comment]
Qbt 4.5.3 is released. See:

https://github.com/qbittorrent/qBittorrent-website/blob/master/news.md

I rebuilt your image using:

docker build https://github.com/DyonR/docker-qbittorrentvpn.git

It now properly exports more than 10 torrents.

**Comment by DyonR** [comment]
Container on Docker Hub updated to qBittorrent 4.5.3

**Comment by gderf** [comment]
Qbt 4.5.4 released on Jun 18, 2023. See:

https://github.com/qbittorrent/qBittorrent-website/blob/master/news.md
