### ISSUE TITLE
Cant access the qbittorrent web UI

### ISSUE THREAD

**Issue by xandervanerven** [DyonR/docker-qbittorrentvpn#17]
Everything starts fine, deamon started
But in the logs folder of qBittorrent i get this error everytime i start the container:
/usr/local/bin/qbittorrent-nox: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
Anyone know how to fix this, would really like to be able to use this nice container!

**Comment by DyonR** [comment]
On what operating system are you running this Docker? Do you use Unraid, Synology or something else?

**Comment by DyonR** [comment]
Also, do you use the Docker Hub image or are you building it yourself?

**Comment by xandervanerven** [comment]
Running in docker version 18.09.0-0513, using your Docker Hub image
DS1515+ DSM 6.2.3-25426 Update 2 Linux 3.10.105 x86_64 GNU/Linux synology_avoton_1515+

**Comment by DyonR** [comment]
This problem seems to be the same as binhex/arch-qbittorrentvpn#3, the user hot22shot has the same issue, also running a synlogoy system with the exact same kernel version as you.  
I am not familiar with synology-system as I said, but updating the kernel of your synology should fix this problem, based on what was told in binhex/arch-qbittorrentvpn#3  
Synology seems to use the Linux Kernel 3.10.105, which was released in February of 2017
It seems like you are already using the latest version of DSM (6.2.3-25426, released 2020-07-16), so I am unsure if updating a kernel would be possible. I'm sorry but it seems like I am unable to do something about this.

**Comment by xandervanerven** [comment]
Ok, that sucks
Ill try to find out if updating the kernel is possible, anyway thanks a lot for the quick help!

**Comment by bhups2k** [comment]
I read somewhere that this command will fix the issue and it does fix it on the build by MarkusMcNugen/docker-qBittorrentvpn
apt update && apt install -y binutils && strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
It is only unfortunate that we are unable to keep the container running for dyonr/qbittorrentvpn to be able to run this in the terminal.
Any pointers will be great.
