### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ciasis** [DyonR/docker-qbittorrentvpn#47]
Hi,
I don't have an issue, but three questions (hope it's okay to open an issue for them here. If not, please move this thread..).

1. When using the container with WireGuard, do I need to forward port 8999 on my router in order to be connectable, too, or is it enough to only open a related port with my VPN provider?

2. I've a question regarding the environment variables `HEALTH_CHECK`. It's not required to set any of these three, but is it useful to use them? If yes, which settings would you advise me to use?

3. To decrease the possibility of IP leaks, would it make sense to also bind the network interface in the qBittorrent WebUI to wg0, or shouldn't I touch this setting, because the IP table rules handle everything correctly?

I'm asking because I already got in trouble once because my IP leaked, and I'm a little concerned and don't want to deal with legal issues and my ISP again, so I want to do everything to prevent IP leaks in the future.

**Comment by DyonR** [comment]
Hi, sorry for the late reply, due personal life I don't spend time working on the Docker any more.  
  
1. You don't need to portforward port 8999. The container connects to your VPN provider via WireGuard, and everything happens on their end. No portforwarding needed, only if you want to access the UI from outside you network.  
2.  You can manually tune them using the environment variables, but if none are set, my recommended settings get applied automatically, since my script check if they have been set.  
3. Binding an interface is not needed. It does connect to the VPN before starting qBittorrent, so no need to worry about that. You ISP could only see that you connect to the IP of your VPN provider, but they don't know what's going on.

Note that running a Docker (of this Docker) is still at your own risk. It has built in protection to block any outcoming or incoming connections that are not your VPN.
